name: Node.js Build Pipeline

on:
  push:
    branches:
      - main  # ya apni desired branch ka naam likhein

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # apni desired Node.js version specify karein

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      - name: Build Application and Capture Logs
        run: |
         npm run build > build.log 2>&1 || {
          echo "Build failed. Outputting log..."
          cat build.log
          exit 1
         }



      # Upload the build logs as artifacts
      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: build.log
        
